title:            SACB Meeting
tagline:          Tag
description:      Systems Approaches to Cancer Biology
baseurl:          /
url:              https://sacbmeeting.org

exclude:
  - README.md
  - Gemfile

sass:
  sass_dir: public/css
  style: :compressed

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true